from dataclasses import make_dataclass
from typing import Dict, List

NAMES: List[str] = [
    "TGFA",
    "EGFR_EGFR",
    "a_EGFR_EGFR",
    "NRG3",
    "ERBB4_ERBB4",
    "a_ERBB4_ERBB4",
    "ERBB4_ERBB2",
    "a_ERBB4_ERBB2",
    "NRG2",
    "ERBB3_ERBB3",
    "a_ERBB3_ERBB3",
    "ERBB3_ERBB2",
    "a_ERBB3_ERBB2",
    "HBEGF",
    "NRG1",
    "EREG",
    "BTC",
    "NRG4",
    "AREG",
    "EGF",
    "ERBB2_ERBB2",
    "SHC2_SHC4_SHC3_SHC1",
    "a_SHC2_SHC4_SHC3_SHC1",
    "GRB2",
    "a_GRB2",
    "PLCG1_PLCG2",
    "a_PLCG1_PLCG2",
    "CBL_CBLB",
    "a_CBL_CBLB",
    "STAT5A_STAT5B",
    "a_STAT5A_STAT5B",
    "CRK_CRKL",
    "a_CRK_CRKL",
    "SRC",
    "a_SRC",
    "NCK1_NCK2",
    "a_NCK1_NCK2",
    "PIK3CA_PIK3CB_PIK3CD_PIK3R1_PIK3R2_PIK3R3",
    "a_PIK3CA_PIK3CB_PIK3CD_PIK3R1_PIK3R2_PIK3R3",
    "AKT3_AKT1_AKT2",
    "a_AKT3_AKT1_AKT2",
    "SOS1_SOS2",
    "a_SOS1_SOS2",
    "GAB1",
    "a_GAB1",
    "CAMK2A_CAMK2B_CAMK2D_CAMK2G",
    "a_CAMK2A_CAMK2B_CAMK2D_CAMK2G",
    "PRKCA_PRKCB_PRKCG",
    "a_PRKCA_PRKCB_PRKCG",
    "MTOR",
    "a_MTOR",
    "BAD",
    "a_BAD",
    "GSK3B",
    "a_GSK3B",
    "CDKN1B",
    "a_CDKN1B",
    "CDKN1A",
    "a_CDKN1A",
    "PAK4_BUB1B_PAK6_PAK1_PAK2_PAK3_PAK6_PAK5",
    "a_PAK4_BUB1B_PAK6_PAK1_PAK2_PAK3_PAK6_PAK5",
    "HRAS_KRAS_NRAS",
    "a_HRAS_KRAS_NRAS",
    "ABL1_ABL2",
    "a_ABL1_ABL2",
    "PTK2",
    "a_PTK2",
    "ARAF_RAF1_BRAF",
    "a_ARAF_RAF1_BRAF",
    "RPS6KB1_RPS6KB2",
    "a_RPS6KB1_RPS6KB2",
    "EIF4EBP1",
    "a_EIF4EBP1",
    "MAP2K7_MAP2K4",
    "a_MAP2K7_MAP2K4",
    "MAP2K1_MAP2K2",
    "a_MAP2K1_MAP2K2",
    "MAPK8_MAPK9_MAPK10",
    "a_MAPK8_MAPK9_MAPK10",
    "MAPK1_MAPK3",
    "a_MAPK1_MAPK3",
    "JUN",
    "a_JUN",
    "ELK1",
    "a_ELK1",
    "MYC",
    "a_MYC",
]

NUM: int = len(NAMES)

Species = make_dataclass(
    cls_name="Species",
    fields=[(name, int) for name in NAMES],
    namespace={"NAMES": NAMES, "NUM": NUM},
    frozen=True,
)

name2idx: Dict[str, int] = {k: v for v, k in enumerate(NAMES)}

V = Species(**name2idx)

del name2idx
